@file:UseSerializers(NonEmptyListSerializer::class)

package it.unibo.osautoupdates.deployment.suite

import arrow.core.serialization.NonEmptyListSerializer
import it.unibo.osautoupdates.deployment.software.SoftwareDeployment
import it.unibo.osautoupdates.software.ResolvedSoftware
import it.unibo.osautoupdates.software.SoftwareName
import it.unibo.osautoupdates.suite.ResolvedSuite
import it.unibo.osautoupdates.suite.Suite.Companion.resolvedSuite
import it.unibo.osautoupdates.util.StringId
import kotlinx.datetime.Clock
import kotlinx.datetime.Instant
import kotlinx.serialization.Contextual
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.UseSerializers

/**
 * The result of a deployment process.
 * @param id the unique identifier of the deployment result. Initially, this field is `null` and is generated by the
 * database.
 * @param resolvedSuite the [ResolvedSoftware]s requested for the deployment.
 * @param softwareDeployments a map consisting of the software name and the corresponding [SoftwareDeployment].
 * @param state the state of the deployment.
 * @param datetime the date and time at which this object has been created. This heavily depends on the last operation
 * performed by the deployment process.
 */
@Serializable
data class SuiteDeployment(
    @SerialName("_id")
    @Contextual
    val id: StringId? = null,
    val resolvedSuite: ResolvedSuite,
    val softwareDeployments: List<SoftwareDeployment>,
    val state: SuiteDeploymentState,
    val datetime: Instant,
) {
    /**
     * @return the [SoftwareDeployment] with the specified [SoftwareName], if any, null otherwise.
     * @param softwareName the name of the software to retrieve.
     * @see SoftwareName
     */
    fun softwareDeployment(softwareName: SoftwareName): SoftwareDeployment? =
        this.softwareDeployments.firstOrNull { it.name == softwareName }

    /**
     * @return the [SoftwareName] of each software deployment in this [SuiteDeployment] without repetitions.
     */
    fun softwareDeploymentsName(): Set<SoftwareName> = this.softwareDeployments.map { it.name }.toSet()

    /**
     * Utility for the [SuiteDeployment] class.
     */
    companion object {
        /**
         * Create an empty deployment, with initial state [SuiteDeploymentState.Started] and the current date and time.
         */
        fun emptyDeployment(): SuiteDeployment =
            SuiteDeployment(
                resolvedSuite = resolvedSuite { },
                softwareDeployments = emptyList(),
                state = SuiteDeploymentState.Started,
                datetime = Clock.System.now(),
            )
    }
}
